### PR TITLE
Add login server to whitelist (Fixes #3)

### LINKED ISSUE #3: can't play music
app can't load music. thanks.

### PR DESCRIPTION
**Pull request by vladdenisov**
**After some researching this problem appeared only while using Spotify with UK VPN.** 
Whitelisting `login5.spotify.com` helped to solve #3

### CODE REVIEW

**Comment by dpatrongomez** [comment]
I just tried it and it is perfect. Now even friends come out

**Comment by vladdenisov** [comment]
I've also tried wrapping this project into npm package, also made little changes (reduced package size and removed useless code). 

You can try it out `npm i -g spotify-proxy` and then just simply run `spotify-proxy`.

all credits go to author of this package.

**Comment by AnanthVivekanand** [comment]
I remember why I had this blocked now. `login5.spotify.com` triggers `spclient.wg.spotify.com` to load ads. Its the same with `heads-fa.scdn.co`. If you either unblock `heads-fa.scdn.co` or `login5.spotify.com`, you trigger the ads. A possible solution could be to block `spclient.wg.spotify.com`. As of right now, I'm not going to merge this PR because its triggering ads for me.

image

Are you receiving any ads on your side?

**Comment by dpatrongomez** [comment]
> I remember why I had this blocked now. `login5.spotify.com` triggers `spclient.wg.spotify.com` to load ads. Its the same with `heads-fa.scdn.co`. If you either unblock `heads-fa.scdn.co` or `login5.spotify.com`, you trigger the ads. A possible solution could be to block `spclient.wg.spotify.com`. As of right now, I'm not going to merge this PR because its triggering ads for me.
> 
> image
> 
> Are you receiving any ads on your side?

Yes, I just found out that I get the same ad

**Comment by vladdenisov** [comment]
strange, but no ads for me. 
So, anyway, this needs more investigating.

**Comment by AnanthVivekanand** [comment]
I'm working on a MITM proxy that will hopefully block every ad while still allowing friends functionality, etc.

It'll have to do SSL decryption though to filter the ads and that will require trusting a Certificate Authority. `spclient.wg.spotify.com` serves friend functionality, ads, and music, so my decrypting that traffic should allow the proxy to sniff and block just the ads.

**Comment by vladdenisov** [comment]
Great. Can you create GitHub repo, so we could help you somehow?

**Comment by AnanthVivekanand** [comment]
After I get it working with basic functionality I'll probably push it to a branch on here :)

**Comment by AnanthVivekanand** [comment]
Yay, basic SSL decryption!!

image

I'll push it soon to a branch named `mitm-proxy`

**Comment by AnanthVivekanand** [comment]
Since we know that this will break adblock functionality for some people, I'm going to close this pull request. A fix for all ads is available on the `mitm-proxy` branch.

**Pull request closed without merging**
